api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Library/Infra/Resources/config/api_platform/resources.xml']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    messenger:
        enabled: true
