api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Library/Infra/Resources/config/api_platform/resources.xml']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    messenger:
        enabled: true
    collection:
        pagination:
            client_items_per_page        : true # Disabled by default
            items_per_page_parameter_name: itemsPerPage # Default value