language: php
sudo: false
cache:
     directories:
        - $HOME/.composer/cache/

env:
    - SYMFONY_VERSION="5.2.*" DB=mysql

services:
    - mysql

php:
    - '7.4'

before-install:
    - composer self-update

install:
    - cp .env.test .env
    - composer install
    - APP_ENV=test php bin/console doctrine:database:create
    - APP_ENV=test php bin/console doctrine:schema:update --force
    - APP_ENV=test php bin/console doctrine:fixtures:load -n

before_script:
    - phpenv config-rm xdebug.ini || return 0

script:
    - bin/phpunit