language: php
sudo: false
cache:
     directories:
        - $HOME/.composer/cache/

warning_are_errors: false

services:
    - mysql

php:
    - '7.4'

install:
    - composer install --prefer-dist --no-interaction
    - APP_ENV=test php bin/console doctrine:database:create
    - APP_ENV=test php bin/console doctrine:schema:update --force
    - APP_ENV=test php bin/console doctrine:fixtures:load -n

before_script:
    - phpenv config-rm xdebug.ini || return 0

script:
    - bin/phpunit