language: php
sudo: false
cache:
     directories:
        - $HOME/.composer/cache

warning_are_errors: false

services:
    - mysql

php:
    - '7.4'

install:
    - composer install --prefer-dist --no-interaction
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:update --force --env=test
    - php bin/console doctrine:fixtures:load -n --env=test

script:
    - bin/phpunit
