# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\Library\:
        resource: '../src/Library/'
        exclude: '../src/Library/{UI, App}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Library\UI\Controller\:
        resource: '../src/Library/UI/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Library\App\CommandHandler\:
        resource: '../src/Library/App/CommandHandler'
        tags:
            - { name: messenger.message_handler, bus: command_bus }

    App\Library\App\QueryHandler\:
        resource: '../src/Library/App/QueryHandler'
        tags:
            - { name: messenger.message_handler, bus: command_bus }

    App\Library\UI\RestNormalizer\:
        resource: '../src/Library/UI/RestNormalizer'
        tags: [ 'serializer.normalizer' ]

    App\Library\Infra\DataTransformer\:
        resource: '../src/Library/Infra/DataTransformer'
        tags: [ 'api_platform.data_transformer' ]